<?php
## This file is generated by mergeMessageFileList.php. Do not edit it directly.

if ( defined( 'MW_NO_EXTENSION_MESSAGES' ) ) return;

$wgExtensionMessagesFiles = array (
  'SystemGiftsAlias' => "$IP/extensions/SocialProfile/SystemGifts/includes/SystemGifts.alias.php",
  'UserActivityAlias' => "$IP/extensions/SocialProfile/UserActivity/includes/UserActivity.alias.php",
  'UserGiftsAlias' => "$IP/extensions/SocialProfile/UserGifts/includes/UserGifts.alias.php",
  'UserRelationshipAlias' => "$IP/extensions/SocialProfile/UserRelationship/UserRelationship.i18n.alias.php",
  'Wikibaseclientalias' => "$IP/extensions/Wikibase/client/WikibaseClient.i18n.alias.php",
  'wikibaseclientmagic' => "$IP/extensions/Wikibase/client/WikibaseClient.i18n.magic.php",
  'WikibaseAlias' => "$IP/extensions/Wikibase/repo/Wikibase.i18n.alias.php",
  'WikibaseNS' => "$IP/extensions/Wikibase/repo/Wikibase.i18n.namespaces.php",
  'wikibaserepomagic' => "$IP/extensions/Wikibase/repo/WikibaseRepo.i18n.magic.php",
  'AbuseFilterAliases' => "$IP/extensions/AbuseFilter/AbuseFilter.alias.php",
  'BetaFeaturesAlias' => "$IP/extensions/BetaFeatures/BetaFeatures.alias.php",
  'SpecialCentralAuthAliases' => "$IP/extensions/CentralAuth/CentralAuth.alias.php",
  'SpecialCentralAuthAliasesNoTranslate' => "$IP/extensions/CentralAuth/CentralAuth.notranslate-alias.php",
  'CentralNoticeAliases' => "$IP/extensions/CentralNotice/CentralNotice.alias.php",
  'CFCachePurgeAlias' => "$IP/extensions/CFCachePurge/CFCachePurge.i18n.alias.php",
  'CheckUserAliases' => "$IP/extensions/CheckUser/CheckUser.alias.php",
  'CreateWikiMagic' => "$IP/extensions/CreateWiki/CreateWikiMagic.php",
  'ConfirmEditAlias' => "$IP/extensions/ConfirmEdit/ConfirmEdit.alias.php",
  'EchoAliases' => "$IP/extensions/Echo/Echo.alias.php",
  'EventLoggingNamespaces' => "$IP/extensions/EventLogging/EventLogging.namespaces.php",
  'GlobalBlockingAlias' => "$IP/extensions/GlobalBlocking/GlobalBlocking.alias.php",
  'GlobalPreferencesAlias' => "$IP/extensions/GlobalPreferences/GlobalPreferences.alias.php",
  'ImportDumpAliases' => "$IP/extensions/ImportDump/ImportDumpAliases.php",
  'ManageWikiAliases' => "$IP/extensions/ManageWiki/ManageWikiAliases.php",
  'NukeAlias' => "$IP/extensions/Nuke/Nuke.alias.php",
  'OATHAuthAlias' => "$IP/extensions/OATHAuth/OATHAuth.alias.php",
  'MWOAuthAliases' => "$IP/extensions/OAuth/MWOAuth.alias.php",
  'OOJSPlusAlias' => "$IP/extensions/OOJSPlus/OOJSPlus.alias.php",
  'ParserFunctionsMagic' => "$IP/extensions/ParserFunctions/ParserFunctions.i18n.magic.php",
  'RemovePIIAliases' => "$IP/extensions/RemovePII/RemovePIIAliases.php",
  'ScribuntoMagic' => "$IP/extensions/Scribunto/Scribunto.magic.php",
  'ScribuntoNamespaces' => "$IP/extensions/Scribunto/Scribunto.namespaces.php",
  'WikiDiscoverAliases' => "$IP/extensions/WikiDiscover/WikiDiscoverAliases.php",
  'WikiDiscoverMagic' => "$IP/extensions/WikiDiscover/WikiDiscoverMagic.php",
  'CategoryTreeAlias' => "$IP/extensions/CategoryTree/CategoryTree.alias.php",
  'CategoryTreeMagic' => "$IP/extensions/CategoryTree/CategoryTree.i18n.magic.php",
  'CiteThisPageAliases' => "$IP/extensions/CiteThisPage/CiteThisPage.alias.php",
  'GlobalUserPageMagic' => "$IP/extensions/GlobalUserPage/GlobalUserPage.i18n.magic.php",
  'MobileFrontendAlias' => "$IP/extensions/MobileFrontend/MobileFrontend.alias.php",
  'UrlShortenerAlias' => "$IP/extensions/UrlShortener/UrlShortener.alias.php",
  'UrlShortenerNoTranslateAlias' => "$IP/extensions/UrlShortener/UrlShortener.notranslate-alias.php",
  'WikiSEOMagic' => "$IP/extensions/WikiSEO/WikiSEO.i18n.magic.php",
  'VisualEditorAlias' => "$IP/extensions/VisualEditor/VisualEditor.i18n.alias.php",
  'TimedMediaHandlerMagic' => "$IP/extensions/TimedMediaHandler/i18n/TimedMediaHandler.i18n.magic.php",
  'TimedMediaHandlerAliases' => "$IP/extensions/TimedMediaHandler/i18n/TimedMediaHandler.i18n.alias.php",
  'BabelMagic' => "$IP/extensions/Babel/Babel.i18n.magic.php",
  'TemplateDataAlias' => "$IP/extensions/TemplateData/TemplateData.i18n.alias.php",
  'UserFunctionsMagic' => "$IP/extensions/UserFunctions/UserFunctions.i18n.magic.php",
  'LinterAlias' => "$IP/extensions/Linter/Linter.alias.php",
  'MassEditRegexAlias' => "$IP/extensions/MassEditRegex/MassEditRegex.alias.php",
  'GadgetsAlias' => "$IP/extensions/Gadgets/Gadgets.alias.php",
  'JsonConfigAliases' => "$IP/extensions/JsonConfig/JsonConfig.aliases.php",
  'JsonConfigNamespaces' => "$IP/extensions/JsonConfig/JsonConfig.namespaces.php",
  'RelatedArticlesMagic' => "$IP/extensions/RelatedArticles/RelatedArticles.i18n.magic.php",
  'ThanksAlias' => "$IP/extensions/Thanks/Thanks.alias.php",
  'DiscussionToolsAlias' => "$IP/extensions/DiscussionTools/DiscussionTools.alias.php",
  'DiscussionToolsMagic' => "$IP/extensions/DiscussionTools/DiscussionTools.magic.php",
  'TranslateAlias' => "$IP/extensions/Translate/i18n/Translate.alias.php",
  'TranslateMagic' => "$IP/extensions/Translate/i18n/Translate.i18n.magic.php",
  'UploadWizardAlias' => "$IP/extensions/UploadWizard/UploadWizard.alias.php",
  'CreatePageAlias' => "$IP/extensions/CreatePage/CreatePage.alias.php",
  'CreatePageMagic' => "$IP/extensions/CreatePage/CreatePage.magic.php",
  'ReplaceTextAlias' => "$IP/extensions/ReplaceText/ReplaceText.i18n.alias.php",
  'AdminLinksAlias' => "$IP/extensions/AdminLinks/AdminLinks.alias.php",
  'EditcountAliases' => "$IP/extensions/Editcount/Editcount.alias.php",
  'SecurePollAlias' => "$IP/extensions/SecurePoll/SecurePoll.alias.php",
  'SecurePollNamespaces' => "$IP/extensions/SecurePoll/SecurePoll.namespaces.php",
  'RequestCustomDomainAliases' => "$IP/extensions/RequestSSL/RequestCustomDomainAliases.php",
  'ApprovedRevsAlias' => "$IP/extensions/ApprovedRevs/ApprovedRevs.alias.php",
  'ApprovedRevsMagic' => "$IP/extensions/ApprovedRevs/ApprovedRevs.i18n.magic.php",
  'ArraysMagic' => "$IP/extensions/Arrays/Arrays.i18n.magic.php",
  'ArticlePlaceholderAliases' => "$IP/extensions/ArticlePlaceholder/ArticlePlaceholder.alias.php",
  'ArticleRatingsAlias' => "$IP/extensions/ArticleRatings/ArticleRatings.alias.php",
  'AutoCreatePageMagic' => "$IP/extensions/AutoCreatePage/AutoCreatePage.i18n.magic.php",
  'BlogPageAlias' => "$IP/extensions/BlogPage/includes/BlogPage.alias.php",
  'BlogPageNamespaces' => "$IP/extensions/BlogPage/includes/BlogPage.namespaces.php",
  'CSSMagic' => "$IP/extensions/CSS/includes/CSS.i18n.magic.php",
  'CalendarMagic' => "$IP/extensions/Calendar/Calendar.i18n.magic.php",
  'CargoMagic' => "$IP/extensions/Cargo/Cargo.i18n.magic.php",
  'CargoAlias' => "$IP/extensions/Cargo/Cargo.alias.php",
  'CategoryExplorerAlias' => "$IP/extensions/CategoryExplorer/CategoryExplorer.alias.php",
  'CategoryTestsMagic' => "$IP/extensions/CategoryTests/CategoryTests.i18n.magic.php",
  'CommentboxAlias' => "$IP/extensions/Commentbox/Commentbox.alias.php",
  'CommentsAliases' => "$IP/extensions/Comments/Comments.i18n.alias.php",
  'CommentsMagic' => "$IP/extensions/Comments/Comments.i18n.magic.php",
  'NumberOfCommentsMagic' => "$IP/extensions/Comments/Comments.i18n.magic.php",
  'ContactPageAliases' => "$IP/extensions/ContactPage/ContactPage.alias.php",
  'ContribScoreAlias' => "$IP/extensions/ContributionScores/ContributionScores.alias.php",
  'ContribScoreMagic' => "$IP/extensions/ContributionScores/ContributionScores.i18n.magic.php",
  'CountDownClockMagic' => "$IP/extensions/CountDownClock/CountDownClock.i18n.magic.php",
  'CreatePageUwAlias' => "$IP/extensions/CreatePageUw/CreatePage.alias.php",
  'CreateRedirectAlias' => "$IP/extensions/CreateRedirect/CreateRedirect.alias.php",
  'CreatedPagesListAlias' => "$IP/extensions/CreatedPagesList/CreatedPagesList.alias.php",
  'CustomSubtitleMagic' => "$IP/extensions/CustomSubtitle/CustomSubtitle.i18n.php",
  'DPLforumMagic' => "$IP/extensions/DPLForum/DPLforum.i18n.magic.php",
  'DPLforumNamespaces' => "$IP/extensions/DPLForum/DPLforum.namespaces.php",
  'DataMapsMagic' => "$IP/extensions/DataMaps/i18n/Magic.php",
  'DataMapsNamespaces' => "$IP/extensions/DataMaps/i18n/Namespaces.php",
  'DataTransferAlias' => "$IP/extensions/DataTransfer/DataTransfer.i18n.alias.php",
  'Description2Magic' => "$IP/extensions/Description2/Description2.i18n.magic.php",
  'DisambiguatorAlias' => "$IP/extensions/Disambiguator/Disambiguator.i18n.alias.php",
  'DisambiguatorMagic' => "$IP/extensions/Disambiguator/Disambiguator.i18n.magic.php",
  'DisplayTitleMagic' => "$IP/extensions/DisplayTitle/includes/DisplayTitle.i18n.magic.php",
  'DraftsAlias' => "$IP/extensions/Drafts/Drafts.alias.php",
  'DynamicPageList4Magic' => "$IP/extensions/DynamicPageList3/DynamicPageList4Magic.php",
  'EmbedVideoMagic' => "$IP/extensions/EmbedVideo/EmbedVideo.i18n.magic.php",
  'EnhancedUploadAlias' => "$IP/extensions/EnhancedUpload/languages/EnhancedUpload.i18n.alias.php",
  'ExternalDataMagic' => "$IP/extensions/ExternalData/ExternalData.i18n.magic.php",
  'ExternalDataAlias' => "$IP/extensions/ExternalData/ExternalData.i18n.alias.php",
  'FeaturedFeedsAliases' => "$IP/extensions/FeaturedFeeds/FeaturedFeeds.alias.php",
  'FlaggedRevsMagic' => "$IP/extensions/FlaggedRevs/includes/frontend/language/FlaggedRevs.i18n.magic.php",
  'FlaggedRevsAliases' => "$IP/extensions/FlaggedRevs/includes/frontend/language/FlaggedRevs.alias.php",
  'FlexDiagramsAlias' => "$IP/extensions/FlexDiagrams/FlexDiagrams.i18n.aliases.php",
  'FlexDiagramsNamespaces' => "$IP/extensions/FlexDiagrams/FlexDiagrams.i18n.namespaces.php",
  'FlexDiagramsMagic' => "$IP/extensions/FlexDiagrams/FlexDiagrams.i18n.magic.php",
  'FlowNamespaces' => "$IP/extensions/Flow/Flow.namespaces.php",
  'FlowAlias' => "$IP/extensions/Flow/Flow.alias.php",
  'FontAwesomeMagic' => "$IP/extensions/FontAwesome/FontAwesome.magic.php",
  'GenealogyMagic' => "$IP/extensions/Genealogy/Genealogy.i18n.magic.php",
  'GeoCrumbsMagic' => "$IP/extensions/GeoCrumbs/GeoCrumbs.i18n.magic.php",
  'GeoDataMagic' => "$IP/extensions/GeoData/GeoData.i18n.magic.php",
  'GlobalNewFilesAliases' => "$IP/extensions/GlobalNewFiles/GlobalNewFilesAliases.php",
  'GlobalUsageAliases' => "$IP/extensions/GlobalUsage/GlobalUsage.alias.php",
  'GlobalWatchlistAliases' => "$IP/extensions/GlobalWatchlist/GlobalWatchlist.alias.php",
  'GoogleNewsSitemapAlias' => "$IP/extensions/GoogleNewsSitemap/GoogleNewsSitemap.alias.php",
  'HeaderTabsMagic' => "$IP/extensions/HeaderTabs/HeaderTabs.i18n.magic.php",
  'IPInfoAliases' => "$IP/extensions/IPInfo/IPInfo.alias.php",
  'ImageRatingAlias' => "$IP/extensions/ImageRating/includes/ImageRating.alias.php",
  'IncidentReportingAliases' => "$IP/extensions/IncidentReporting/IncidentReportingAliases.php",
  'JavascriptSlideshowMagic' => "$IP/extensions/JavascriptSlideshow/JavascriptSlideshow.i18n.magic.php",
  'JosaMagic' => "$IP/extensions/Josa/Josa.i18n.magic.php",
  'KartographerAliases' => "$IP/extensions/Kartographer/Kartographer.alias.php",
  'LabeledSectionTransclusionMagic' => "$IP/extensions/LabeledSectionTransclusion/LabeledSectionTransclusion.i18n.magic.php",
  'LingoMagic' => "$IP/extensions/Lingo/src/Lingo.i18n.magic.php",
  'LinkCardsMagic' => "$IP/extensions/LinkCards/LinkCards.i18n.magic.php",
  'LinkTitlesMagic' => "$IP/extensions/LinkTitles/includes/Magic.php",
  'LogoFunctionsMagic' => "$IP/extensions/LogoFunctions/LogoFunctions.i18n.magic.php",
  'LoopsMagic' => "$IP/extensions/Loops/Loops.i18n.magic.php",
  'MagicNoCacheMagic' => "$IP/extensions/MagicNoCache/MagicNoCache.i18n.magic.php",
  'MapsAlias' => "$IP/extensions/Maps/i18n/aliases/Aliases.php",
  'MapsMagic' => "$IP/extensions/Maps/i18n/magic/MagicWords.php",
  'MassMessageAlias' => "$IP/extensions/MassMessage/MassMessage.alias.php",
  'MassMessageMagic' => "$IP/extensions/MassMessage/MassMessage.i18n.magic.php",
  'MathAlias' => "$IP/extensions/Math/Math.alias.php",
  'MathAliasNoTranslate' => "$IP/extensions/Math/Math.alias.noTranslate.php",
  'MatomoAnalyticsAliases' => "$IP/extensions/MatomoAnalytics/MatomoAnalyticsAliases.php",
  'MediaSearchAlias' => "$IP/extensions/MediaSearch/MediaSearch.i18n.alias.php",
  'MediaWikiChatAlias' => "$IP/extensions/MediaWikiChat/MediaWikiChat.alias.php",
  'MermaidMagic' => "$IP/extensions/Mermaid/i18n/extra/Mermaid.magic.php",
  'MintyDocsMagic' => "$IP/extensions/MintyDocs/MintyDocs.i18n.magic.php",
  'MintyDocsNS' => "$IP/extensions/MintyDocs/MintyDocsNamespaces.php",
  'MintyDocsAlias' => "$IP/extensions/MintyDocs/MintyDocs.i18n.alias.php",
  'MirahezeMagicAliases' => "$IP/extensions/MirahezeMagic/MirahezeMagicAliases.php",
  'MobileDetectMagic' => "$IP/extensions/MobileDetect/MobileDetect.i18n.magic.php",
  'ModerationAlias' => "$IP/extensions/Moderation/Moderation.alias.php",
  'MsLinksMagic' => "$IP/extensions/MsLinks/MsLinks.i18n.magic.php",
  'MultiBoilerplateAlias' => "$IP/extensions/MultiBoilerplate/MultiBoilerplate.alias.php",
  'MultiPurgeAlias' => "$IP/extensions/MultiPurge/MultiPurge.alias.php",
  'MyVariablesMagic' => "$IP/extensions/MyVariables/MyVariables.i18n.magic.php",
  'NearbyAliases' => "$IP/extensions/NearbyPages/NearbyPages.alias.php",
  'NetworkParserFunction' => "$IP/extensions/Network/i18n/_MagicWords.php",
  'NetworkAlias' => "$IP/extensions/Network/i18n/Network.i18n.alias.php",
  'NewestPagesAlias' => "$IP/extensions/NewestPages/NewestPages.alias.php",
  'NewsletterAlias' => "$IP/extensions/Newsletter/Newsletter.alias.php",
  'NewsletterNamespaces' => "$IP/extensions/Newsletter/Newsletter.namespaces.php",
  'NoTitleMagic' => "$IP/extensions/NoTitle/NoTitle.i18n.magic.php",
  'NukeDPLAliases' => "$IP/extensions/NukeDPL/NukeDPL.alias.php",
  'OpenGraphMetaMagic' => "$IP/extensions/OpenGraphMeta/OpenGraphMeta.magic.php",
  'OreDictMagic' => "$IP/extensions/OreDict/OreDict.i18n.magic.php",
  'OrphanedTalkPagesAlias' => "$IP/extensions/OrphanedTalkPages/OrphanedTalkPages.alias.php",
  'PWAMagic' => "$IP/extensions/PWA/PWA.i18n.php",
  'PageAssessmentsMagic' => "$IP/extensions/PageAssessments/PageAssessments.i18n.magic.php",
  'PageAssessmentsAlias' => "$IP/extensions/PageAssessments/PageAssessments.i18n.alias.php",
  'PageFormsAlias' => "$IP/extensions/PageForms/languages/PF_Aliases.php",
  'PageFormsMagic' => "$IP/extensions/PageForms/languages/PF_Magic.php",
  'PageFormsNS' => "$IP/extensions/PageForms/languages/PF_Namespaces.php",
  'PageLanguageMagic' => "$IP/extensions/PageLanguage/PageLanguage.magic.php",
  'PagePropertiesAlias' => "$IP/extensions/PageProperties/PageProperties.alias.php",
  'PageSchemasAlias' => "$IP/extensions/PageSchemas/PageSchemas.i18n.alias.php",
  'PageTriageAlias' => "$IP/extensions/PageTriage/PageTriage.alias.php",
  'PagedTiffHandlerMagic' => "$IP/extensions/PagedTiffHandler/PagedTiffHandler.i18n.magic.php",
  'PhonosMagic' => "$IP/extensions/Phonos/Phonos.i18n.php",
  'PipeEscapeMagic' => "$IP/extensions/PipeEscape/PipeEscape.i18n.magic.php",
  'PollNYAlias' => "$IP/extensions/PollNY/includes/PollNY.alias.php",
  'PollNYNamespaces' => "$IP/extensions/PollNY/includes/PollNY.namespaces.php",
  'PortableInfoboxAliases' => "$IP/extensions/PortableInfobox/PortableInfoboxAliases.php",
  'PortableInfoboxMagic' => "$IP/extensions/PortableInfobox/PortableInfoboxMagic.php",
  'ProofreadPageAlias' => "$IP/extensions/ProofreadPage/ProofreadPage.alias.php",
  'ProofreadPageMagic' => "$IP/extensions/ProofreadPage/ProofreadPage.i18n.php",
  'PropertySuggesterAlias' => "$IP/extensions/PropertySuggester/PropertySuggester.alias.php",
  'ProtectSiteAliases' => "$IP/extensions/ProtectSite/ProtectSite.alias.php",
  'QuizGameAlias' => "$IP/extensions/QuizGame/includes/QuizGame.alias.php",
  'RandomSelectionMagic' => "$IP/extensions/RandomSelection/RandomSelection.i18n.magic.php",
  'RatePageMagic' => "$IP/extensions/RatePage/RatePage.magic.php",
  'RatePageAlias' => "$IP/extensions/RatePage/RatePage.alias.php",
  'RegexFunctionsMagic' => "$IP/extensions/RegexFunctions/RegexFunctions.i18n.magic.php",
  'ReportAlias' => "$IP/extensions/Report/Report.i18n.alias.php",
  'RightFunctionsMagic' => "$IP/extensions/RightFunctions/RightFunctions.i18n.magic.php",
  'RottenLinksAliases' => "$IP/extensions/RottenLinks/RottenLinksAliases.php",
  'RottenLinksMagic' => "$IP/extensions/RottenLinks/RottenLinksMagic.php",
  'ShortDescriptionMagic' => "$IP/extensions/ShortDescription/ShortDescription.i18n.magic.php",
  'SimpleBatchUploadAlias' => "$IP/extensions/SimpleBatchUpload/src/SimpleBatchUpload.alias.php",
  'SimpleBatchUploadMagic' => "$IP/extensions/SimpleBatchUpload/src/SimpleBatchUpload.magic.php",
  'SimpleBlogPageAliases' => "$IP/extensions/SimpleBlogPage/SimpleBlogPageAliases.php",
  'SimpleBlogPageNamespaces' => "$IP/extensions/SimpleBlogPage/SimpleBlogPageNamespaces.php",
  'SimpleChangesAlias' => "$IP/extensions/SimpleChanges/SimpleChanges.alias.php",
  'SimpleTooltipMagic' => "$IP/extensions/SimpleTooltip/SimpleTooltip.i18n.magic.php",
  'SkinPerPageMagic' => "$IP/extensions/SkinPerPage/SkinPerPage.i18n.magic.php",
  'SoftRedirectorAlias' => "$IP/extensions/SoftRedirector/SoftRedirector.i18n.alias.php",
  'SoftRedirectorMagic' => "$IP/extensions/SoftRedirector/SoftRedirector.i18n.magic.php",
  'SpoilersMagic' => "$IP/extensions/Spoilers/SpoilersI18nMagic.php",
  'StructuredNavigationNamespaces' => "$IP/extensions/StructuredNavigation/StructuredNavigation.i18n.namespaces.php",
  'StructuredNavigationAliases' => "$IP/extensions/StructuredNavigation/StructuredNavigation.i18n.aliases.php",
  'SubpageFunMagic' => "$IP/extensions/SubpageFun/SubpageFun.i18n.magic.php",
  'TabsMagic' => "$IP/extensions/Tabs/Tabs.i18n.magic.php",
  'TemplateSandboxAlias' => "$IP/extensions/TemplateSandbox/TemplateSandbox.alias.php",
  'SpecialTilesheets' => "$IP/extensions/Tilesheets/Tilesheets.alias.php",
  'TilesheetsMagic' => "$IP/extensions/Tilesheets/Tilesheets.i18n.magic.php",
  'TimeMachineAlias' => "$IP/extensions/TimeMachine/TimeMachine.alias.php",
  'TimezoneConverterMagic' => "$IP/extensions/TimezoneConverter/TimezoneConverter.i18n.magic.php",
  'TitleIconMagic' => "$IP/extensions/TitleIcon/i18n/TitleIconMagic.i18n.php",
  'TreeAndMenuMagic' => "$IP/extensions/TreeAndMenu/TreeAndMenu.i18n.magic.php",
  'TwoColConflictAlias' => "$IP/extensions/TwoColConflict/TwoColConflict.alias.php",
  'UnlinkedWikibaseMagicWords' => "$IP/extensions/UnlinkedWikibase/UnlinkedWikibase.i18n.magic.php",
  'UnlinkedWikibaseAliases' => "$IP/extensions/UnlinkedWikibase/UnlinkedWikibase.i18n.aliases.php",
  'UnusedRedirectsAlias' => "$IP/extensions/UnusedRedirects/UnusedRedirects.alias.php",
  'UrlGetParametersMagic' => "$IP/extensions/UrlGetParameters/UrlGetParameters.i18n.magic.php",
  'UserProfileV2Aliases' => "$IP/extensions/UserProfileV2/UserProfileV2.alias.php",
  'VariablesMagic' => "$IP/extensions/Variables/Variables.i18n.magic.php",
  'VideoAlias' => "$IP/extensions/Video/includes/Video.alias.php",
  'VideoNamespaces' => "$IP/extensions/Video/includes/Video.namespaces.php",
  'VoteNYAlias' => "$IP/extensions/VoteNY/includes/VoteNY.alias.php",
  'VoteNYMagic' => "$IP/extensions/VoteNY/includes/VoteNY.i18n.magic.php",
  'WebChatAlias' => "$IP/extensions/WebChat/WebChat.alias.php",
  'WidgetsMagic' => "$IP/extensions/Widgets/Widgets.i18n.magic.php",
  'WidgetsNamespaces' => "$IP/extensions/Widgets/Widgets.i18n.namespaces.php",
  'WikiForumAlias' => "$IP/extensions/WikiForum/includes/WikiForum.i18n.alias.php",
  'WikibaseCirrusSearchAlias' => "$IP/extensions/WikibaseCirrusSearch/WikibaseCirrusSearch.alias.php",
  'WikibaseLexemeAlias' => "$IP/extensions/WikibaseLexeme/WikibaseLexeme.i18n.alias.php",
  'WikibaseQualityConstraintsAlias' => "$IP/extensions/WikibaseQualityConstraints/WikibaseQualityConstraints.alias.php",
  'WikidataPageBannerMagic' => "$IP/extensions/WikidataPageBanner/WikidataPageBanner.i18n.magic.php",
  'WikimediaIncubatorAlias' => "$IP/extensions/WikimediaIncubator/WikimediaIncubator.alias.php",
  'WikimediaIncubatorMagic' => "$IP/extensions/WikimediaIncubator/WikimediaIncubator.i18n.magic.php",
  'HieroglyphsAlias' => "$IP/extensions/wikihiero/wikihiero.alias.php",
  'SocialProfileAlias' => "$IP/extensions/SocialProfile/SocialProfile.alias.php",
  'SocialProfileNamespaces' => "$IP/extensions/SocialProfile/SocialProfile.namespaces.php",
  'AvatarMagic' => "$IP/extensions/SocialProfile/UserProfile/includes/avatar/Avatar.i18n.magic.php",
  'ParserHooksExtension' => "$IP/extensions/Maps/vendor/mediawiki/parser-hooks/ParserHooks.i18n.php",
  'RobloxAPIMagic' => "$IP/extensions/RobloxAPI/RobloxAPI.i18n.magic.php",
  'TweekiMagic' => "$IP/skins/Tweeki/Tweeki.i18n.magic.php",
  'CosmosAliases' => "$IP/skins/Cosmos/CosmosAliases.php",
  'CosmosMagic' => "$IP/skins/Cosmos/CosmosMagic.php",
);

$wgMessagesDirs = array (
  'SystemGifts' => 
  array (
    0 => "$IP/extensions/SocialProfile/SystemGifts/i18n",
  ),
  'UserActivity' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserActivity/i18n",
  ),
  'UserBoard' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserBoard/i18n",
  ),
  'UserGifts' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserGifts/i18n",
  ),
  'UserRelationship' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserRelationship/i18n",
  ),
  'UserStats' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserStats/i18n",
  ),
  'UserWelcome' => 
  array (
    0 => "$IP/extensions/SocialProfile/UserWelcome/i18n",
  ),
  'wikibaseclient' => 
  array (
    0 => "$IP/extensions/Wikibase/client/i18n",
  ),
  'wikibaseclientapi' => 
  array (
    0 => "$IP/extensions/Wikibase/client/i18n/api",
  ),
  'WikibaseLib' => 
  array (
    0 => "$IP/extensions/Wikibase/lib/i18n",
    1 => "$IP/extensions/Wikibase/lib/i18n",
  ),
  'Wikibase' => 
  array (
    0 => "$IP/extensions/Wikibase/repo/i18n",
  ),
  'WikibaseApi' => 
  array (
    0 => "$IP/extensions/Wikibase/repo/i18n/api",
  ),
  'WikibaseView' => 
  array (
    0 => "$IP/extensions/Wikibase/view/lib/wikibase-data-values-value-view/i18n",
  ),
  'Cosmos' =>
  array (
    0 => "$IP/skins/Cosmos/i18n",
  ),
  'Citizen' => 
  array (
    0 => "$IP/skins/Citizen/i18n",
  ),
  'CologneBlue' => 
  array (
    0 => "$IP/skins/CologneBlue/i18n",
  ),
  'Modern' => 
  array (
    0 => "$IP/skins/Modern/i18n",
  ),
  'MonoBook' => 
  array (
    0 => "$IP/skins/MonoBook/i18n",
  ),
  'Timeless' => 
  array (
    0 => "$IP/skins/Timeless/i18n",
  ),
  'Vector' => 
  array (
    0 => "$IP/skins/Vector/i18n",
  ),
  'Tweeki' => 
  array (
    0 => "$IP/skins/Tweeki/i18n",
  ),
  'AbuseFilter' => 
  array (
    0 => "$IP/extensions/AbuseFilter/i18n",
    1 => "$IP/extensions/AbuseFilter/i18n/api",
  ),
  'AntiSpoof' => 
  array (
    0 => "$IP/extensions/AntiSpoof/i18n",
    1 => "$IP/extensions/AntiSpoof/i18n/api",
  ),
  'AWS' => 
  array (
    0 => "$IP/extensions/AWS/i18n",
  ),
  'BetaFeatures' => 
  array (
    0 => "$IP/extensions/BetaFeatures/i18n",
    1 => "$IP/extensions/BetaFeatures/i18n/api",
  ),
  'SpecialCentralAuth' => 
  array (
    0 => "$IP/extensions/CentralAuth/i18n",
    1 => "$IP/extensions/CentralAuth/i18n/api",
  ),
  'CentralNotice' => 
  array (
    0 => "$IP/extensions/CentralNotice/i18n",
    1 => "$IP/extensions/CentralNotice/i18n/api",
  ),
  'CFCachePurge' => 
  array (
    0 => "$IP/extensions/CFCachePurge/i18n",
  ),
  'CheckUser' => 
  array (
    0 => "$IP/extensions/CheckUser/i18n",
    1 => "$IP/extensions/CheckUser/i18n/api",
  ),
  'CreateWiki' => 
  array (
    0 => "$IP/extensions/CreateWiki/i18n",
  ),
  'CookieWarning' => 
  array (
    0 => "$IP/extensions/CookieWarning/i18n",
  ),
  'ConfirmEdit' => 
  array (
    0 => "$IP/extensions/ConfirmEdit/i18n",
    1 => "$IP/extensions/ConfirmEdit/i18n/api",
  ),
  'hCaptcha' => 
  array (
    0 => "$IP/extensions/ConfirmEdit/i18n/hCaptcha",
  ),
  'DataDump' => 
  array (
    0 => "$IP/extensions/DataDump/i18n",
  ),
  'DiscordNotifications' => 
  array (
    0 => "$IP/extensions/DiscordNotifications/i18n",
  ),
  'DismissableSiteNotice' => 
  array (
    0 => "$IP/extensions/DismissableSiteNotice/i18n",
  ),
  'Echo' => 
  array (
    0 => "$IP/extensions/Echo/i18n",
    1 => "$IP/extensions/Echo/i18n/api",
  ),
  'EventLogging' => 
  array (
    0 => "$IP/extensions/EventLogging/i18n/core",
  ),
  'JsonSchema' => 
  array (
    0 => "$IP/extensions/EventLogging/i18n/jsonschema",
  ),
  'GlobalBlocking' => 
  array (
    0 => "$IP/extensions/GlobalBlocking/i18n",
    1 => "$IP/extensions/GlobalBlocking/i18n/api",
  ),
  'GlobalCssJs' => 
  array (
    0 => "$IP/extensions/GlobalCssJs/i18n/core",
  ),
  'GlobalPreferences' => 
  array (
    0 => "$IP/extensions/GlobalPreferences/i18n",
    1 => "$IP/extensions/GlobalPreferences/i18n/api",
  ),
  'ImportDump' => 
  array (
    0 => "$IP/extensions/ImportDump/i18n",
  ),
  'InterwikiDispatcher' => 
  array (
    0 => "$IP/extensions/InterwikiDispatcher/i18n",
  ),
  'LoginNotify' => 
  array (
    0 => "$IP/extensions/LoginNotify/i18n",
  ),
  'ManageWiki' => 
  array (
    0 => "$IP/extensions/ManageWiki/i18n",
  ),
  'NativeSvgHandler' => 
  array (
    0 => "$IP/extensions/NativeSvgHandler/i18n",
  ),
  'Nuke' => 
  array (
    0 => "$IP/extensions/Nuke/i18n",
  ),
  'OATHAuth' => 
  array (
    0 => "$IP/extensions/OATHAuth/i18n",
    1 => "$IP/extensions/OATHAuth/i18n/api",
  ),
  'MWOAuth' => 
  array (
    0 => "$IP/extensions/OAuth/i18n",
  ),
  'OOJSPlus' => 
  array (
    0 => "$IP/extensions/OOJSPlus/i18n",
  ),
  'ParserFunctions' => 
  array (
    0 => "$IP/extensions/ParserFunctions/i18n",
  ),
  'QuickInstantCommons' => 
  array (
    0 => "$IP/extensions/QuickInstantCommons/i18n",
  ),
  'RemovePII' => 
  array (
    0 => "$IP/extensions/RemovePII/i18n",
  ),
  'Scribunto' => 
  array (
    0 => "$IP/extensions/Scribunto/i18n",
    1 => "$IP/extensions/Scribunto/i18n/api",
  ),
  'SpamBlackList' => 
  array (
    0 => "$IP/extensions/SpamBlacklist/i18n",
    1 => "$IP/extensions/SpamBlacklist/i18n/api",
  ),
  'TitleBlacklist' => 
  array (
    0 => "$IP/extensions/TitleBlacklist/i18n",
    1 => "$IP/extensions/TitleBlacklist/i18n/api",
  ),
  'TorBlock' => 
  array (
    0 => "$IP/extensions/TorBlock/i18n",
    1 => "$IP/extensions/TorBlock/i18n/api",
  ),
  'WikiDiscover' => 
  array (
    0 => "$IP/extensions/WikiDiscover/i18n",
  ),
  'WikiEditor' => 
  array (
    0 => "$IP/extensions/WikiEditor/i18n",
  ),
  'WikiOasisMagic' => 
  array (
    0 => "$IP/extensions/WikiOasisMagic/i18n/wikioasis",
  ),
  'CLDR' => 
  array (
    0 => "$IP/extensions/cldr/i18n",
  ),
  'CategoryTree' => 
  array (
    0 => "$IP/extensions/CategoryTree/i18n",
    1 => "$IP/extensions/CategoryTree/i18n/api",
  ),
  'Cite' => 
  array (
    0 => "$IP/extensions/Cite/i18n",
    1 => "$IP/extensions/Cite/modules/ve-cite/i18n",
  ),
  'CiteThisPage' => 
  array (
    0 => "$IP/extensions/CiteThisPage/i18n",
  ),
  'CodeEditor' => 
  array (
    0 => "$IP/extensions/CodeEditor/i18n",
  ),
  'CodeMirror' => 
  array (
    0 => "$IP/extensions/CodeMirror/i18n",
  ),
  'DarkMode' => 
  array (
    0 => "$IP/extensions/DarkMode/i18n",
  ),
  'GlobalUserPage' => 
  array (
    0 => "$IP/extensions/GlobalUserPage/i18n",
  ),
  'MinervaNeue' => 
  array (
    0 => "$IP/skins/MinervaNeue/i18n",
  ),
  'MobileFrontend' => 
  array (
    0 => "$IP/extensions/MobileFrontend/i18n",
    1 => "$IP/extensions/MobileFrontend/i18n/api",
  ),
  'SyntaxHighlight_GeSHi' => 
  array (
    0 => "$IP/extensions/SyntaxHighlight_GeSHi/i18n",
  ),
  'TextExtracts' => 
  array (
    0 => "$IP/extensions/TextExtracts/i18n",
    1 => "$IP/extensions/TextExtracts/i18n/api",
  ),
  'UrlShortener' => 
  array (
    0 => "$IP/extensions/UrlShortener/i18n",
    1 => "$IP/extensions/UrlShortener/i18n/api",
  ),
  'WikiSEO' => 
  array (
    0 => "$IP/extensions/WikiSEO/i18n",
  ),
  'PageImages' => 
  array (
    0 => "$IP/extensions/PageImages/i18n",
    1 => "$IP/extensions/PageImages/i18n/api",
  ),
  'VisualEditor' => 
  array (
    0 => "$IP/extensions/VisualEditor/lib/ve/i18n",
    1 => "$IP/extensions/VisualEditor/i18n/ve-mw",
    2 => "$IP/extensions/VisualEditor/i18n/ve-mw/api",
    3 => "$IP/extensions/VisualEditor/i18n/ve-mw/mwlanguagevariant",
    4 => "$IP/extensions/VisualEditor/i18n/ve-wmf",
    5 => "$IP/extensions/VisualEditor/editcheck/i18n",
    6 => "$IP/extensions/VisualEditor/editcheck/i18n/api",
  ),
  'TimedMediaHandler' => 
  array (
    0 => "$IP/extensions/TimedMediaHandler/i18n",
    1 => "$IP/extensions/TimedMediaHandler/i18n/api",
  ),
  'Babel' => 
  array (
    0 => "$IP/extensions/Babel/i18n",
    1 => "$IP/extensions/Babel/i18n/api",
  ),
  'Timeline' => 
  array (
    0 => "$IP/extensions/Timeline/i18n",
  ),
  'ImageMap' => 
  array (
    0 => "$IP/extensions/ImageMap/i18n",
  ),
  'InputBox' => 
  array (
    0 => "$IP/extensions/InputBox/i18n",
  ),
  'Poem' => 
  array (
    0 => "$IP/extensions/Poem/i18n",
  ),
  'TemplateData' => 
  array (
    0 => "$IP/extensions/TemplateData/i18n",
    1 => "$IP/extensions/TemplateData/i18n/api",
  ),
  'TemplateStyles' => 
  array (
    0 => "$IP/extensions/TemplateStyles/i18n",
  ),
  'UserFunctions' => 
  array (
    0 => "$IP/extensions/UserFunctions/i18n",
  ),
  'Linter' => 
  array (
    0 => "$IP/extensions/Linter/i18n",
    1 => "$IP/extensions/Linter/i18n/api",
  ),
  'MassEditRegex' => 
  array (
    0 => "$IP/extensions/MassEditRegex/i18n",
  ),
  'Gadgets' => 
  array (
    0 => "$IP/extensions/Gadgets/i18n",
    1 => "$IP/extensions/Gadgets/i18n/api",
  ),
  'JsonConfig' => 
  array (
    0 => "$IP/extensions/JsonConfig/i18n",
    1 => "$IP/extensions/JsonConfig/i18n/api",
  ),
  'RelatedArticles' => 
  array (
    0 => "$IP/extensions/RelatedArticles/i18n",
  ),
  'RevisionSlider' => 
  array (
    0 => "$IP/extensions/RevisionSlider/i18n",
  ),
  'UniversalLanguageSelector' => 
  array (
    0 => "$IP/extensions/UniversalLanguageSelector/i18n",
    1 => "$IP/extensions/UniversalLanguageSelector/i18n/api",
    2 => "$IP/extensions/UniversalLanguageSelector/i18n/api/languagesearch",
  ),
  'Thanks' => 
  array (
    0 => "$IP/extensions/Thanks/i18n",
    1 => "$IP/extensions/Thanks/i18n/api",
  ),
  'DiscussionTools' => 
  array (
    0 => "$IP/extensions/DiscussionTools/i18n",
    1 => "$IP/extensions/DiscussionTools/i18n/api",
  ),
  'PageTranslation' => 
  array (
    0 => "$IP/extensions/Translate/i18n/pagetranslation",
  ),
  'Translate' => 
  array (
    0 => "$IP/extensions/Translate/i18n/core",
  ),
  'TranslateApi' => 
  array (
    0 => "$IP/extensions/Translate/i18n/api",
  ),
  'TranslateSandbox' => 
  array (
    0 => "$IP/extensions/Translate/i18n/sandbox",
  ),
  'TranslateSearch' => 
  array (
    0 => "$IP/extensions/Translate/i18n/search",
  ),
  'UploadWizard' => 
  array (
    0 => "$IP/extensions/UploadWizard/i18n",
    1 => "$IP/extensions/UploadWizard/i18n/api",
  ),
  'Preloader' => 
  array (
    0 => "$IP/extensions/Preloader/i18n",
  ),
  'TemplateStylesExtender' => 
  array (
    0 => "$IP/extensions/TemplateStylesExtender/i18n",
  ),
  'CreatePage' => 
  array (
    0 => "$IP/extensions/CreatePage/i18n",
  ),
  'Purge' => 
  array (
    0 => "$IP/extensions/Purge/i18n",
  ),
  'WikiTextLoggedInOut' => 
  array (
    0 => "$IP/extensions/WikiTextLoggedInOut/i18n",
  ),
  'DynamicSidebar' => 
  array (
    0 => "$IP/extensions/DynamicSidebar/i18n",
  ),
  'ReplaceText' => 
  array (
    0 => "$IP/extensions/ReplaceText/i18n",
  ),
  'Popups' => 
  array (
    0 => "$IP/extensions/Popups/i18n",
  ),
  'AJAXPoll' => 
  array (
    0 => "$IP/extensions/AJAXPoll/i18n",
  ),
  'AdminLinks' => 
  array (
    0 => "$IP/extensions/AdminLinks/i18n",
  ),
  'Editcount' => 
  array (
    0 => "$IP/extensions/Editcount/i18n",
  ),
  'SecurePoll' => 
  array (
    0 => "$IP/extensions/SecurePoll/i18n",
    1 => "$IP/extensions/SecurePoll/i18n/api",
  ),
  'RequestCustomDomain' => 
  array (
    0 => "$IP/extensions/RequestSSL/i18n",
  ),
  '3D' => 
  array (
    0 => "$IP/extensions/3D/i18n",
  ),
  'AdvancedSearch' => 
  array (
    0 => "$IP/extensions/AdvancedSearch/i18n",
  ),
  'ApprovedRevs' => 
  array (
    0 => "$IP/extensions/ApprovedRevs/i18n",
  ),
  'Arrays' => 
  array (
    0 => "$IP/extensions/Arrays/i18n",
  ),
  'ArticleCreationWorkflow' => 
  array (
    0 => "$IP/extensions/ArticleCreationWorkflow/i18n",
  ),
  'ArticlePlaceholder' => 
  array (
    0 => "$IP/extensions/ArticlePlaceholder/i18n",
  ),
  'ArticleRatings' => 
  array (
    0 => "$IP/extensions/ArticleRatings/i18n",
    1 => "$IP/extensions/ArticleRatings/i18n/api",
  ),
  'ArticleToCategory2' => 
  array (
    0 => "$IP/extensions/ArticleToCategory2/i18n",
  ),
  'AuthorProtect' => 
  array (
    0 => "$IP/extensions/AuthorProtect/i18n",
  ),
  'AutoCreateCategoryPages' => 
  array (
    0 => "$IP/extensions/AutoCreateCategoryPages/i18n",
  ),
  'AutoCreatePage' => 
  array (
    0 => "$IP/extensions/AutoCreatePage/i18n",
  ),
  'BlogPage' => 
  array (
    0 => "$IP/extensions/BlogPage/i18n",
  ),
  'Bootstrap' => 
  array (
    0 => "$IP/extensions/Bootstrap/i18n",
  ),
  'CSS' => 
  array (
    0 => "$IP/extensions/CSS/i18n",
  ),
  'Calendar' => 
  array (
    0 => "$IP/extensions/Calendar/i18n",
  ),
  'Capiunto' => 
  array (
    0 => "$IP/extensions/Capiunto/i18n",
  ),
  'Cargo' => 
  array (
    0 => "$IP/extensions/Cargo/i18n",
    1 => "$IP/extensions/Cargo/i18n/api",
  ),
  'categoryexplorer' => 
  array (
    0 => "$IP/extensions/CategoryExplorer/i18n",
  ),
  'CategorySortHeaders' => 
  array (
    0 => "$IP/extensions/CategorySortHeaders/i18n",
  ),
  'CategoryTests' => 
  array (
    0 => "$IP/extensions/CategoryTests/i18n",
  ),
  'CharInsert' => 
  array (
    0 => "$IP/extensions/CharInsert/i18n",
  ),
  'CirrusSearch' => 
  array (
    0 => "$IP/extensions/CirrusSearch/i18n",
    1 => "$IP/extensions/CirrusSearch/i18n/api",
  ),
  'Citoid' => 
  array (
    0 => "$IP/extensions/Citoid/i18n",
  ),
  'CleanChanges' => 
  array (
    0 => "$IP/extensions/CleanChanges/i18n",
  ),
  'CollapsibleVector' => 
  array (
    0 => "$IP/extensions/CollapsibleVector/i18n",
  ),
  'CommentStreams' => 
  array (
    0 => "$IP/extensions/CommentStreams/i18n",
  ),
  'Commentbox' => 
  array (
    0 => "$IP/extensions/Commentbox/i18n",
  ),
  'Comments' => 
  array (
    0 => "$IP/extensions/Comments/i18n",
  ),
  'CommonsMetadata' => 
  array (
    0 => "$IP/extensions/CommonsMetadata/i18n",
  ),
  'ContactPage' => 
  array (
    0 => "$IP/extensions/ContactPage/i18n",
  ),
  'ContributionScores' => 
  array (
    0 => "$IP/extensions/ContributionScores/i18n",
  ),
  'CountDownClock' => 
  array (
    0 => "$IP/extensions/CountDownClock/i18n",
  ),
  'CreatePageUw' => 
  array (
    0 => "$IP/extensions/CreatePageUw/i18n",
  ),
  'CreateRedirect' => 
  array (
    0 => "$IP/extensions/CreateRedirect/i18n",
  ),
  'CreatedPagesList' => 
  array (
    0 => "$IP/extensions/CreatedPagesList/i18n",
  ),
  'CustomSearchProfiles' => 
  array (
    0 => "$IP/extensions/CustomSearchProfiles/i18n",
  ),
  'CustomSubtitle' => 
  array (
    0 => "$IP/extensions/CustomSubtitle/i18n",
  ),
  'DPLforum' => 
  array (
    0 => "$IP/extensions/DPLForum/i18n",
  ),
  'DataMaps' => 
  array (
    0 => "$IP/extensions/DataMaps/i18n/core",
    1 => "$IP/extensions/DataMaps/i18n/createmap",
    2 => "$IP/extensions/DataMaps/i18n/ve",
  ),
  'DataTransfer' => 
  array (
    0 => "$IP/extensions/DataTransfer/i18n",
  ),
  'DeleteUserPages' => 
  array (
    0 => "$IP/extensions/DeleteUserPages/i18n",
  ),
  'Description2' => 
  array (
    0 => "$IP/extensions/Description2/i18n",
  ),
  'Disambiguator' => 
  array (
    0 => "$IP/extensions/Disambiguator/i18n",
  ),
  'DisplayTitle' => 
  array (
    0 => "$IP/extensions/DisplayTitle/i18n",
  ),
  'Drafts' => 
  array (
    0 => "$IP/extensions/Drafts/i18n",
  ),
  'DummyFandoomMainpageTags' => 
  array (
    0 => "$IP/extensions/DummyFandoomMainpageTags/i18n",
  ),
  'DynamicPageList' => 
  array (
    0 => "$IP/extensions/DynamicPageList/i18n",
  ),
  'DynamicPageList4' => 
  array (
    0 => "$IP/extensions/DynamicPageList3/i18n",
  ),
  'EditSubpages' => 
  array (
    0 => "$IP/extensions/EditSubpages/i18n",
  ),
  'Elastica' => 
  array (
    0 => "$IP/extensions/Elastica/i18n",
  ),
  'EmbedVideo' => 
  array (
    0 => "$IP/extensions/EmbedVideo/i18n",
  ),
  'EnhancedUpload' => 
  array (
    0 => "$IP/extensions/EnhancedUpload/i18n",
  ),
  'EventBus' => 
  array (
    0 => "$IP/extensions/EventBus/i18n",
  ),
  'EventStreamConfig' => 
  array (
    0 => "$IP/extensions/EventStreamConfig/i18n",
  ),
  'ExternalData' => 
  array (
    0 => "$IP/extensions/ExternalData/i18n",
  ),
  'FeaturedFeeds' => 
  array (
    0 => "$IP/extensions/FeaturedFeeds/i18n",
    1 => "$IP/extensions/FeaturedFeeds/i18n/api",
  ),
  'FlaggedRevs' => 
  array (
    0 => "$IP/extensions/FlaggedRevs/i18n/flaggedrevs",
    1 => "$IP/extensions/FlaggedRevs/i18n/revisionreview",
    2 => "$IP/extensions/FlaggedRevs/i18n/stabilization",
    3 => "$IP/extensions/FlaggedRevs/i18n/unreviewedpages",
    4 => "$IP/extensions/FlaggedRevs/i18n/pendingchanges",
    5 => "$IP/extensions/FlaggedRevs/i18n/stablepages",
    6 => "$IP/extensions/FlaggedRevs/i18n/configuredpages",
    7 => "$IP/extensions/FlaggedRevs/i18n/validationstatistics",
    8 => "$IP/extensions/FlaggedRevs/i18n/api",
  ),
  'FlexDiagrams' => 
  array (
    0 => "$IP/extensions/FlexDiagrams/i18n",
  ),
  'Flow' => 
  array (
    0 => "$IP/extensions/Flow/i18n",
    1 => "$IP/extensions/Flow/i18n/api",
  ),
  'FontAwesome' => 
  array (
    0 => "$IP/extensions/FontAwesome/i18n",
  ),
  'ForcePreview' => 
  array (
    0 => "$IP/extensions/ForcePreview/i18n",
  ),
  'GTag' => 
  array (
    0 => "$IP/extensions/GTag/i18n",
  ),
  'Genealogy' => 
  array (
    0 => "$IP/extensions/Genealogy/i18n",
  ),
  'GeoCrumbs' => 
  array (
    0 => "$IP/extensions/GeoCrumbs/i18n",
  ),
  'GeoData' => 
  array (
    0 => "$IP/extensions/GeoData/i18n",
    1 => "$IP/extensions/GeoData/i18n/api",
  ),
  'GeoGebra' => 
  array (
    0 => "$IP/extensions/GeoGebra/i18n",
  ),
  'GlobalNewFiles' => 
  array (
    0 => "$IP/extensions/GlobalNewFiles/i18n",
  ),
  'GlobalUsage' => 
  array (
    0 => "$IP/extensions/GlobalUsage/i18n",
    1 => "$IP/extensions/GlobalUsage/i18n/api",
  ),
  'GlobalWatchlist' => 
  array (
    0 => "$IP/extensions/GlobalWatchlist/i18n",
  ),
  'GoogleDocs4MW' => 
  array (
    0 => "$IP/extensions/GoogleDocs4MW/i18n",
  ),
  'GoogleForms' => 
  array (
    0 => "$IP/extensions/GoogleForms/i18n",
  ),
  'GoogleNewsSitemap' => 
  array (
    0 => "$IP/extensions/GoogleNewsSitemap/i18n",
  ),
  'GroupsSidebar' => 
  array (
    0 => "$IP/extensions/GroupsSidebar/i18n",
  ),
  'GuidedTour' => 
  array (
    0 => "$IP/extensions/GuidedTour/i18n",
  ),
  'HAWelcome' => 
  array (
    0 => "$IP/extensions/HAWelcome/i18n",
  ),
  'HeaderTabs' => 
  array (
    0 => "$IP/extensions/HeaderTabs/i18n",
  ),
  'HideSection' => 
  array (
    0 => "$IP/extensions/HideSection/i18n",
  ),
  'HighlightLinksInCategory' => 
  array (
    0 => "$IP/extensions/HighlightLinksInCategory/i18n",
  ),
  'IPInfo' => 
  array (
    0 => "$IP/extensions/IPInfo/i18n",
  ),
  'ImageRating' => 
  array (
    0 => "$IP/extensions/ImageRating/i18n",
  ),
  'IncidentReporting' => 
  array (
    0 => "$IP/extensions/IncidentReporting/i18n",
  ),
  'InterwikiSorting' => 
  array (
    0 => "$IP/extensions/InterwikiSorting/i18n",
  ),
  'JSBreadCrumbs' => 
  array (
    0 => "$IP/extensions/JSBreadCrumbs/i18n",
  ),
  'JavascriptSlideshow' => 
  array (
    0 => "$IP/extensions/JavascriptSlideshow/i18n",
  ),
  'Josa' => 
  array (
    0 => "$IP/extensions/Josa/i18n",
  ),
  'Kartographer' => 
  array (
    0 => "$IP/extensions/Kartographer/i18n",
    1 => "$IP/extensions/Kartographer/i18n/api",
    2 => "$IP/extensions/Kartographer/modules/wikivoyage/i18n",
  ),
  'LabeledSectionTransclusion' => 
  array (
    0 => "$IP/extensions/LabeledSectionTransclusion/i18n",
  ),
  'LanguageSelector' => 
  array (
    0 => "$IP/extensions/LanguageSelector/i18n",
  ),
  'LastModified' => 
  array (
    0 => "$IP/extensions/LastModified/i18n",
  ),
  'Lingo' => 
  array (
    0 => "$IP/extensions/Lingo/i18n",
  ),
  'LinkCards' => 
  array (
    0 => "$IP/extensions/LinkCards/i18n",
  ),
  'LinkSuggest' => 
  array (
    0 => "$IP/extensions/LinkSuggest/i18n",
  ),
  'LinkTarget' => 
  array (
    0 => "$IP/extensions/LinkTarget/i18n",
  ),
  'LinkTitles' => 
  array (
    0 => "$IP/extensions/LinkTitles/i18n",
  ),
  'LockAuthor' => 
  array (
    0 => "$IP/extensions/LockAuthor/i18n",
  ),
  'LogoFunctions' => 
  array (
    0 => "$IP/extensions/LogoFunctions/i18n",
  ),
  'Loops' => 
  array (
    0 => "$IP/extensions/Loops/i18n",
  ),
  'MagicNoCache' => 
  array (
    0 => "$IP/extensions/MagicNoCache/i18n",
  ),
  'Maps.class' => 
  array (
    0 => "$IP/extensions/Maps/i18n",
  ),
  'MassMessage' => 
  array (
    0 => "$IP/extensions/MassMessage/i18n",
    1 => "$IP/extensions/MassMessage/i18n/api",
  ),
  'Math' => 
  array (
    0 => "$IP/extensions/Math/i18n",
    1 => "$IP/extensions/Math/i18n/api",
  ),
  'MatomoAnalytics' => 
  array (
    0 => "$IP/extensions/MatomoAnalytics/i18n",
  ),
  'MediaSearch' => 
  array (
    0 => "$IP/extensions/MediaSearch/i18n",
  ),
  'MediaSpoiler' => 
  array (
    0 => "$IP/extensions/MediaSpoiler/i18n",
  ),
  'MediaWikiChat' => 
  array (
    0 => "$IP/extensions/MediaWikiChat/i18n",
  ),
  'Mermaid' => 
  array (
    0 => "$IP/extensions/Mermaid/i18n",
  ),
  'MintyDocs' => 
  array (
    0 => "$IP/extensions/MintyDocs/i18n",
  ),
  'MirahezeMagic' => 
  array (
    0 => "$IP/extensions/MirahezeMagic/i18n/overrides",
    1 => "$IP/extensions/MirahezeMagic/i18n/miraheze",
    2 => "$IP/extensions/MirahezeMagic/i18n/mirahezeprojectnames",
  ),
  'MobileDetect' => 
  array (
    0 => "$IP/extensions/MobileDetect/i18n",
  ),
  'Moderation' => 
  array (
    0 => "$IP/extensions/Moderation/i18n",
    1 => "$IP/extensions/Moderation/api/i18n",
  ),
  'MsCalendar' => 
  array (
    0 => "$IP/extensions/MsCalendar/i18n",
  ),
  'MsCatSelect' => 
  array (
    0 => "$IP/extensions/MsCatSelect/i18n",
  ),
  'MsLinks' => 
  array (
    0 => "$IP/extensions/MsLinks/i18n",
  ),
  'MsUpload' => 
  array (
    0 => "$IP/extensions/MsUpload/i18n",
  ),
  'MultiBoilerplate' => 
  array (
    0 => "$IP/extensions/MultiBoilerplate/i18n",
  ),
  'MultiPurge' => 
  array (
    0 => "$IP/extensions/MultiPurge/i18n",
  ),
  'MultimediaViewer' => 
  array (
    0 => "$IP/extensions/MultimediaViewer/i18n",
  ),
  'MyVariables' => 
  array (
    0 => "$IP/extensions/MyVariables/i18n",
  ),
  'NamespacePreload' => 
  array (
    0 => "$IP/extensions/NamespacePreload/i18n",
  ),
  'NearbyPages' => 
  array (
    0 => "$IP/extensions/NearbyPages/i18n",
  ),
  'Network' => 
  array (
    0 => "$IP/extensions/Network/i18n",
  ),
  'NewSignupPage' => 
  array (
    0 => "$IP/extensions/NewSignupPage/i18n",
  ),
  'NewUserMessage' => 
  array (
    0 => "$IP/extensions/NewUserMessage/i18n",
  ),
  'NewUserNotif' => 
  array (
    0 => "$IP/extensions/NewUserNotif/i18n",
  ),
  'NewestPages' => 
  array (
    0 => "$IP/extensions/NewestPages/i18n",
  ),
  'Newsletter' => 
  array (
    0 => "$IP/extensions/Newsletter/i18n",
    1 => "$IP/extensions/Newsletter/i18n/api",
  ),
  'NoTitle' => 
  array (
    0 => "$IP/extensions/NoTitle/i18n",
  ),
  'NukeDPL' => 
  array (
    0 => "$IP/extensions/NukeDPL/i18n",
  ),
  'OpenGraphMeta' => 
  array (
    0 => "$IP/extensions/OpenGraphMeta/i18n",
  ),
  'OreDict' => 
  array (
    0 => "$IP/extensions/OreDict/i18n",
  ),
  'OrphanedTalkPages' => 
  array (
    0 => "$IP/extensions/OrphanedTalkPages/i18n",
  ),
  'PDFEmbed' => 
  array (
    0 => "$IP/extensions/PDFEmbed/i18n",
  ),
  'PWA' => 
  array (
    0 => "$IP/extensions/PWA/i18n",
  ),
  'PageAssessments' => 
  array (
    0 => "$IP/extensions/PageAssessments/i18n",
    1 => "$IP/extensions/PageAssessments/i18n/api",
  ),
  'PageForms' => 
  array (
    0 => "$IP/extensions/PageForms/i18n",
  ),
  'PageLanguage' => 
  array (
    0 => "$IP/extensions/PageLanguage/i18n",
  ),
  'PageNotice' => 
  array (
    0 => "$IP/extensions/PageNotice/i18n",
  ),
  'PageProperties' => 
  array (
    0 => "$IP/extensions/PageProperties/i18n",
  ),
  'PageSchemas' => 
  array (
    0 => "$IP/extensions/PageSchemas/i18n",
  ),
  'PageTriage' => 
  array (
    0 => "$IP/extensions/PageTriage/i18n",
  ),
  'PagedTiffHandler' => 
  array (
    0 => "$IP/extensions/PagedTiffHandler/i18n",
  ),
  'ParserMigration' => 
  array (
    0 => "$IP/extensions/ParserMigration/i18n",
    1 => "$IP/extensions/ParserMigration/i18n/api",
  ),
  'PdfHandler' => 
  array (
    0 => "$IP/extensions/PdfHandler/i18n",
  ),
  'PerPageLanguage' => 
  array (
    0 => "$IP/extensions/PerPageLanguage/i18n",
  ),
  'Phonos' => 
  array (
    0 => "$IP/extensions/Phonos/i18n",
  ),
  'PipeEscape' => 
  array (
    0 => "$IP/extensions/PipeEscape/i18n",
  ),
  'PollNY' => 
  array (
    0 => "$IP/extensions/PollNY/i18n",
  ),
  'PortableInfobox' => 
  array (
    0 => "$IP/extensions/PortableInfobox/i18n",
  ),
  'ProofreadPage' => 
  array (
    0 => "$IP/extensions/ProofreadPage/i18n",
    1 => "$IP/extensions/ProofreadPage/i18n/api",
  ),
  'PropertySuggester' => 
  array (
    0 => "$IP/extensions/PropertySuggester/i18n",
    1 => "$IP/extensions/PropertySuggester/i18n/api",
  ),
  'ProtectSite' => 
  array (
    0 => "$IP/extensions/ProtectSite/i18n",
  ),
  'ProtectionIndicator' => 
  array (
    0 => "$IP/extensions/ProtectionIndicator/i18n",
  ),
  'QuizExtension' => 
  array (
    0 => "$IP/extensions/Quiz/i18n",
  ),
  'QuizGame' => 
  array (
    0 => "$IP/extensions/QuizGame/i18n",
  ),
  'RSS' => 
  array (
    0 => "$IP/extensions/RSS/i18n",
  ),
  'RandomGameUnit' => 
  array (
    0 => "$IP/extensions/RandomGameUnit/i18n",
  ),
  'RandomImage' => 
  array (
    0 => "$IP/extensions/RandomImage/i18n",
  ),
  'RandomSelection' => 
  array (
    0 => "$IP/extensions/RandomSelection/i18n",
  ),
  'RatePage' => 
  array (
    0 => "$IP/extensions/RatePage/i18n",
    1 => "$IP/extensions/RatePage/i18n/api",
  ),
  'RealMe' => 
  array (
    0 => "$IP/extensions/RealMe/i18n",
  ),
  'RegexFunctions' => 
  array (
    0 => "$IP/extensions/RegexFunctions/i18n",
  ),
  'RemoveRedlinks' => 
  array (
    0 => "$IP/extensions/RemoveRedlinks/i18n",
  ),
  'Report' => 
  array (
    0 => "$IP/extensions/Report/i18n",
  ),
  'ReportIncident' => 
  array (
    0 => "$IP/extensions/ReportIncident/i18n",
  ),
  'RightFunctions' => 
  array (
    0 => "$IP/extensions/RightFunctions/i18n",
  ),
  'RottenLinks' => 
  array (
    0 => "$IP/extensions/RottenLinks/i18n",
  ),
  'SandboxLink' => 
  array (
    0 => "$IP/extensions/SandboxLink/i18n",
  ),
  'Score' => 
  array (
    0 => "$IP/extensions/Score/i18n",
  ),
  'Screenplay' => 
  array (
    0 => "$IP/extensions/Screenplay/i18n",
  ),
  'SecureLinkFixer' => 
  array (
    0 => "$IP/extensions/SecureLinkFixer/i18n",
  ),
  'Share' => 
  array (
    0 => "$IP/extensions/Share/i18n",
  ),
  'ShortDescription' => 
  array (
    0 => "$IP/extensions/ShortDescription/i18n",
    1 => "$IP/extensions/ShortDescription/i18n/api",
  ),
  'SimpleBatchUpload' => 
  array (
    0 => "$IP/extensions/SimpleBatchUpload/i18n",
  ),
  'SimpleBlogPage' => 
  array (
    0 => "$IP/extensions/SimpleBlogPage/i18n",
  ),
  'SimpleChanges' => 
  array (
    0 => "$IP/extensions/SimpleChanges/i18n",
  ),
  'SimpleTooltip' => 
  array (
    0 => "$IP/extensions/SimpleTooltip/i18n",
  ),
  'SkinPerPage' => 
  array (
    0 => "$IP/extensions/SkinPerPage/i18n",
  ),
  'EmbedSnap' => 
  array (
    0 => "$IP/extensions/SnapProjectEmbed/i18n",
  ),
  'SoftRedirector' => 
  array (
    0 => "$IP/extensions/SoftRedirector/i18n",
  ),
  'SpeciallyCursed' => 
  array (
    0 => "$IP/extensions/SpeciallyCursed/i18n",
  ),
  'Spoilers' => 
  array (
    0 => "$IP/extensions/Spoilers/i18n",
  ),
  'StandardDialogs' => 
  array (
    0 => "$IP/extensions/StandardDialogs/i18n",
  ),
  'StopForumSpam' => 
  array (
    0 => "$IP/extensions/StopForumSpam/i18n",
  ),
  'StructuredNavigation' => 
  array (
    0 => "$IP/extensions/StructuredNavigation/i18n",
    1 => "$IP/extensions/StructuredNavigation/i18n/api",
  ),
  'SubPageList3' => 
  array (
    0 => "$IP/extensions/SubPageList3/i18n",
  ),
  'SubpageFun' => 
  array (
    0 => "$IP/extensions/SubpageFun/i18n",
  ),
  'TabberNeue' => 
  array (
    0 => "$IP/extensions/TabberNeue//i18n",
  ),
  'Tabs' => 
  array (
    0 => "$IP/extensions/Tabs/i18n",
  ),
  'TemplateSandbox' => 
  array (
    0 => "$IP/extensions/TemplateSandbox/i18n",
    1 => "$IP/extensions/TemplateSandbox/i18n/api",
  ),
  'TemplateWizard' => 
  array (
    0 => "$IP/extensions/TemplateWizard/i18n",
  ),
  'Theme' => 
  array (
    0 => "$IP/extensions/Theme/i18n",
  ),
  'Tilesheets' => 
  array (
    0 => "$IP/extensions/Tilesheets/i18n",
  ),
  'TimeMachine' => 
  array (
    0 => "$IP/extensions/TimeMachine/i18n",
  ),
  'TimezoneConverter' => 
  array (
    0 => "$IP/extensions/TimezoneConverter/i18n",
  ),
  'TitleIcon' => 
  array (
    0 => "$IP/extensions/TitleIcon/i18n",
  ),
  'TitleKey' => 
  array (
    0 => "$IP/extensions/TitleKey/i18n",
  ),
  'TocTree' => 
  array (
    0 => "$IP/extensions/TocTree/i18n",
  ),
  'TranslationNotifications' => 
  array (
    0 => "$IP/extensions/TranslationNotifications/i18n",
  ),
  'TreeAndMenu' => 
  array (
    0 => "$IP/extensions/TreeAndMenu/i18n",
  ),
  'TwitterTag' => 
  array (
    0 => "$IP/extensions/TwitterTag/i18n",
  ),
  'TwoColConflict' => 
  array (
    0 => "$IP/extensions/TwoColConflict/i18n",
  ),
  'UnlinkedWikibase' => 
  array (
    0 => "$IP/extensions/UnlinkedWikibase/i18n",
  ),
  'UnusedRedirects' => 
  array (
    0 => "$IP/extensions/UnusedRedirects/i18n",
  ),
  'UploadsLink' => 
  array (
    0 => "$IP/extensions/UploadsLink/i18n",
  ),
  'UrlGetParameters' => 
  array (
    0 => "$IP/extensions/UrlGetParameters/i18n",
  ),
  'UserPageEditProtection' => 
  array (
    0 => "$IP/extensions/UserPageEditProtection/i18n",
  ),
  'UserProfileV2' => 
  array (
    0 => "$IP/extensions/UserProfileV2/i18n",
  ),
  'VEForAll' => 
  array (
    0 => "$IP/extensions/VEForAll/i18n",
  ),
  'Variables' => 
  array (
    0 => "$IP/extensions/Variables/i18n",
  ),
  'VariablesLua' => 
  array (
    0 => "$IP/extensions/VariablesLua/i18n",
  ),
  'Video' => 
  array (
    0 => "$IP/extensions/Video/i18n",
  ),
  'VoteNY' => 
  array (
    0 => "$IP/extensions/VoteNY/i18n",
  ),
  'WebAuthn' => 
  array (
    0 => "$IP/extensions/WebAuthn/i18n",
    1 => "$IP/extensions/WebAuthn/i18n/api",
  ),
  'WebChat' => 
  array (
    0 => "$IP/extensions/WebChat/i18n",
  ),
  'Widgets' => 
  array (
    0 => "$IP/extensions/Widgets/i18n",
  ),
  'WikiCategoryTagCloud' => 
  array (
    0 => "$IP/extensions/WikiCategoryTagCloud/i18n",
  ),
  'WikiForum' => 
  array (
    0 => "$IP/extensions/WikiForum/i18n",
    1 => "$IP/extensions/WikiForum/i18n/api",
  ),
  'WikiLove' => 
  array (
    0 => "$IP/extensions/WikiLove/i18n",
    1 => "$IP/extensions/WikiLove/i18n/api",
  ),
  'WikibaseCirrusSearch' => 
  array (
    0 => "$IP/extensions/WikibaseCirrusSearch/i18n",
    1 => "$IP/extensions/WikibaseLexemeCirrusSearch/i18n",
  ),
  'WikibaseEDTF' => 
  array (
    0 => "$IP/extensions/WikibaseEdtf/i18n",
  ),
  'WikibaseLexeme' => 
  array (
    0 => "$IP/extensions/WikibaseLexeme/i18n",
    1 => "$IP/extensions/WikibaseLexeme/i18n/api",
  ),
  'WikibaseLocalMedia' => 
  array (
    0 => "$IP/extensions/WikibaseLocalMedia/i18n",
  ),
  'WikibaseMediaInfo' => 
  array (
    0 => "$IP/extensions/WikibaseMediaInfo/i18n",
  ),
  'WikibaseQualityConstraints' => 
  array (
    0 => "$IP/extensions/WikibaseQualityConstraints/i18n",
    1 => "$IP/extensions/WikibaseQualityConstraints/i18n/api",
  ),
  'WikidataPageBanner' => 
  array (
    0 => "$IP/extensions/WikidataPageBanner/i18n",
  ),
  'WikimediaIncubator' => 
  array (
    0 => "$IP/extensions/WikimediaIncubator/i18n/core",
    1 => "$IP/extensions/WikimediaIncubator/i18n/onwikimessages",
  ),
  'YouTube' => 
  array (
    0 => "$IP/extensions/YouTube/i18n",
  ),
  'ScratchBlocks4' => 
  array (
    0 => "$IP/extensions/mw-ScratchBlocks4/i18n",
  ),
  'SnapBlocks' => 
  array (
    0 => "$IP/extensions/mw-snapblocks/i18n",
  ),
  'Wikihiero' => 
  array (
    0 => "$IP/extensions/wikihiero/i18n",
  ),
  'RobloxAPI' => 
  array (
    0 => "$IP/extensions/RobloxAPI/i18n",
  ),
  'MediaModeration' => 
  array (
    0 => "$IP/extensions/MediaModeration/i18n",
  ),
  'mwstake-component-formengine' => "$IP/extensions/OOJSPlus/vendor/mwstake/mediawiki-component-formengine/i18n",
  'SocialProfile' => "$IP/extensions/SocialProfile/i18n",
  'SocialProfileUserProfile' => "$IP/extensions/SocialProfile/UserProfile/i18n",
  'ParserHooksExtension' => "$IP/extensions/Maps/vendor/mediawiki/parser-hooks/i18n",
);
