<?php
wfLoadSkins( [
	'Citizen',
	'CologneBlue',
	'Modern',
	'MonoBook',
	'Timeless',
	'Vector',
] );

wfLoadExtensions( [
    'AbuseFilter',
    'AntiSpoof',
    'AWS',
    'BetaFeatures',
    'CentralAuth',
    'CentralNotice',
    'CFCachePurge',
    'CheckUser',
    'CreateWiki',
    'CookieWarning',
    'ConfirmEdit',
    'ConfirmEdit/hCaptcha',
    'DataDump',
    'DiscordNotifications',
    'DismissableSiteNotice',
    'Echo',
    'EventBus',
    'EventLogging',
    'EventStreamConfig',
    'GlobalBlocking',
    'GlobalCssJs',
    'GlobalPreferences',
    'GTag',
    //'GlobalNewFiles',
    'ImportDump',
    'Interwiki',
    'InterwikiDispatcher',
    //'IPInfo',
    'LoginNotify',
    'ManageWiki',
    'MediaModeration',
    //'MatomoAnalytics',
    //'MobileDetect',
    //'MultiPurge',
    //'NativeSvgHandler',
    'Nuke',
    'OATHAuth',
    'OAuth',
    'OOJSPlus',
    'ParserFunctions',
    'ParserMigration',
    'QuickInstantCommons',
    'RemovePII',
    // 'ReportIncident',
    //'RottenLinks',
    'Scribunto',
    // 'SecureLinkFixer',
    'SpamBlacklist',
    // 'StopForumSpam',
    'TitleBlacklist',
    'TorBlock',
    //'WebAuthn',
    'WikiDiscover',
    'WikiEditor',
	'WikiOasisMagic',
    'cldr',
] );

$wgEventLoggingBaseUri = '/beacon/event';
$wgEventLoggingServiceUri = '/beacon/intake-analytics';
$wgEventLoggingStreamNames = false;
