<?php
wfLoadSkins( [
	'Citizen',
	'CologneBlue',
	'Modern',
	'MonoBook',
	'Timeless',
	'Vector',
] );

wfLoadExtensions( [
    'AbuseFilter',
    'AntiSpoof',
    'AWS',
    'BetaFeatures',
    'CentralAuth',
    'CentralNotice',
    'CFCachePurge',
    'CheckUser',
    'CreateWiki',
    'CookieWarning',
    'Compass',
    'ConfirmEdit',
    'ConfirmEdit/hCaptcha',
    'DataDump',
    'DiscordNotifications',
    'DismissableSiteNotice',
    'Echo',
    'EventBus',
    'EventLogging',
    'GlobalBlocking',
    'GlobalCssJs',
    'GlobalPreferences',
    'ImportDump',
    'InterwikiDispatcher',
    'LoginNotify',
    'ManageWiki',
    'MediaModeration',
    'Nuke',
    'OATHAuth',
    'OAuth',
    'OOJSPlus',
    'ParserFunctions',
    'ParserMigration',
    'QuickInstantCommons',
    'RemovePII',
    'Scribunto',
    'SpamBlacklist',
    'Spring',
    'TitleBlacklist',
    'TorBlock',
    'WikiEditor',
    'WikiOasisMagic',
    'WikiOasisSafety',
    'WikimediaEvents',
    'cldr',
] );
